// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhaYE9FkwGNmNqpBE6uEijssUWcAe3Stw',
    appId: '1:1016482599849:web:11a1d7c583fa2b39f92ab8',
    messagingSenderId: '1016482599849',
    projectId: 'attendence-tracker-3a766',
    authDomain: 'attendence-tracker-3a766.firebaseapp.com',
    storageBucket: 'attendence-tracker-3a766.firebasestorage.app',
    measurementId: 'G-H2JBM397W3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4w7647a8btizuG5L20-qGnC7ou3YU18Q',
    appId: '1:1016482599849:android:df90e4aa7d6cd8b9f92ab8',
    messagingSenderId: '1016482599849',
    projectId: 'attendence-tracker-3a766',
    storageBucket: 'attendence-tracker-3a766.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWhKosuG6RFKCkSuHK3awoARValeePo9I',
    appId: '1:1016482599849:ios:ae06f3bd6c32d591f92ab8',
    messagingSenderId: '1016482599849',
    projectId: 'attendence-tracker-3a766',
    storageBucket: 'attendence-tracker-3a766.firebasestorage.app',
    iosClientId:
        '1016482599849-sfbl8lojii6l7lsd8g3b2olvstl5nm92.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendenceTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWhKosuG6RFKCkSuHK3awoARValeePo9I',
    appId: '1:1016482599849:ios:ae06f3bd6c32d591f92ab8',
    messagingSenderId: '1016482599849',
    projectId: 'attendence-tracker-3a766',
    storageBucket: 'attendence-tracker-3a766.firebasestorage.app',
    iosClientId:
        '1016482599849-sfbl8lojii6l7lsd8g3b2olvstl5nm92.apps.googleusercontent.com',
    iosBundleId: 'com.example.attendenceTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhaYE9FkwGNmNqpBE6uEijssUWcAe3Stw',
    appId: '1:1016482599849:web:288b6d4637d9163bf92ab8',
    messagingSenderId: '1016482599849',
    projectId: 'attendence-tracker-3a766',
    authDomain: 'attendence-tracker-3a766.firebaseapp.com',
    storageBucket: 'attendence-tracker-3a766.firebasestorage.app',
    measurementId: 'G-2VM8K1T4XD',
  );
}
